### ISSUE TITLE
Exp Route Tool: Species-Label Sync

### ISSUE THREAD

**Issue by gav-antula** [Corvimae/pokemon-ranger#10]
When typing in a Pokemon's name into the Species dropdown, the auto-filling fields below it (Label + Base Experience) sometimes do not "catch up" to the name you land on. For example, I was typing in "Meowth" to find Meowth-galar. I arrived at the Species name, but the auto-fill information landed on "Muk-alola". Another example was typing in for "Durant" and getting the autofill for "Duraludon-Gmax". If I click "Add" in its current state, the Exp projection will be for Alolan Muk, not Galarian Meowth. As I've been typing in the names, I would estimate this glitch occurs about 10-15% of the time. 

![dropdownsync1](https://user-images.githubusercontent.com/90369070/132619542-2b3c034c-d2de-4b8c-ae3c-8dac339fcdfd.png)
![dropdownsync2](https://user-images.githubusercontent.com/90369070/132619546-ec012f50-d4a9-43e1-9e3f-fb5de946c0f7.png)

As of now the easy workaround is just to select another name from the list, and then reselect the intended name. However this is dependant on me noticing the mis-sync before clicking add.

**Comment by Corvimae** [comment]
What browser are you using? I'm not sure I'm able to reproduce this on Firefox.

**Comment by gav-antula** [comment]
Chrome

**Comment by Corvimae** [comment]
Hopefully fixed, please confirm.
