### ISSUE TITLE
EXP Router Requests

### ISSUE THREAD

**Issue by gav-antula** [Corvimae/pokemon-ranger#15]
Some suggestions for easier use:
- Option to add Experience Event or Rare Candy to the top of the existing Experience Route (or to insert into a specific point in the list)
- Toggle to sort species list Alphabetically rather than by Pokedex number
- Separate [Experience Event] section into [Your Pokemon] and [Event Pokemon]. Currently the options for the Pokemon gaining the experience and the Pokemon giving experience are intermingled, making it confusing to know whether the prompt is for your Pokemon or the opponent's. For example, I don't know whether "Past Evolution Level" is about the Pokemon I'm routing or the event Pokemon.
- Option to select a specific event already in the Route Builder and edit it
- Option to minimize/hide portion of the Exp Route to declutter the page (Ex: hide up to Level 34) 
- Vertical scrollbar for the Route (or have Exp Route Builder section follow you as scrolling down the page)

**Comment by Corvimae** [comment]
> Option to add Experience Event or Rare Candy to the top of the existing Experience Route (or to insert into a specific point in the list)

Implemented.

> Toggle to sort species list Alphabetically rather than by Pokedex number

Selector now has typeahead support instead, should hopefully work well enough.
> Separate [Experience Event] section into [Your Pokemon] and [Event Pokemon]. Currently the options for the Pokemon gaining the experience and the Pokemon giving experience are intermingled, making it confusing to know whether the prompt is for your Pokemon or the opponent's. For example, I don't know whether "Past Evolution Level" is about the Pokemon I'm routing or the event Pokemon.

Implemented.

>  Option to select a specific event already in the Route Builder and edit it.

Please resubmit as a separate issue so that I don't lose track of this (it's a non-trivial change 😔 )

>  Option to minimize/hide portion of the Exp Route to declutter the page (Ex: hide up to Level 34)

Same with this, will require more work.

>  Vertical scrollbar for the Route (or have Exp Route Builder section follow you as scrolling down the page)

Implemented
