### ISSUE TITLE
Routes - Damage calculations are inaccurate

### ISSUE THREAD

**Issue by dlchoi91** [Corvimae/pokemon-ranger#17]
The damage calc on routes are not showing correct damage calcs. for example, on the alpha sapphire any% route, the damage calcs are not the actual damage that is being dealt. 

nosepass damage calc:
![image](https://user-images.githubusercontent.com/46817190/134784099-4f9935a0-ad79-4182-baf7-59c3840a13a7.png)

hideki calc:
![image](https://user-images.githubusercontent.com/46817190/134784135-e75e4c8f-2304-4f72-ab4c-bfecc2083c3c.png)

**Comment by Corvimae** [comment]
Fixed, sorry about that.
