### ISSUE TITLE
The right pane when viewing a route doesn't respect light theme when toggled on.

### ISSUE THREAD

**Issue by yaycupcake** [Corvimae/pokemon-ranger#22]
I am unsure if this is an error or an oversight or something simply not being planned, but as dark theme is difficult for some people (like myself) to read (white text on dark background can look very blurry to some folks with astigmatism, to the point it's unreadable and unusable) it may be helpful for accessibility if the light/dark theme toggle respected the pane with the actual range calculations, to match the left pane with other information on the route itself. Thanks for your time and consideration.

![image](https://user-images.githubusercontent.com/11069809/144741475-dae19c11-f9e2-46d5-804f-448e4d76dbea.png)

**Comment by Corvimae** [comment]
Light mode was the original theme, so when I implemented dark mode I didn’t think to change the sidebar. I can definitely change the sidebar color, so you have a suggested background color?

**Comment by yaycupcake** [comment]
I think a pure white could be fine, since that's what the left pane seems to have. But also it could be helpful to have a more subdued color like `whitesmoke` or `antiquewhite` to differentiate. At least for me, I actually prefer to have sites in general have off-whites as opposed to pure white, but that's just the opinion of one individual here.

**Comment by Corvimae** [comment]
I won’t have time to fix this until after the weekend, but in the interim you can recollect the sidebar in the options menu after opening the route.

**Comment by Corvimae** [comment]
This should be fixed now.
