### ISSUE TITLE
"Exp. Needed" Tool Error

### ISSUE THREAD

**Issue by gav-antula** [Corvimae/pokemon-ranger#23]
The "Experience Needed to Next Level Up" works as intended most of the time. However when the last experience event is hidden, it produces an error (NaN). 
![Switch-on](https://user-images.githubusercontent.com/90369070/145919435-bc2d1f71-b91a-4a17-9e60-a65d04a17501.png)
vs.
![Switch-off](https://user-images.githubusercontent.com/90369070/145919430-565290ab-0024-4db5-bd55-663ca12568d3.png)

**Comment by Corvimae** [comment]
Fixed
