### ISSUE TITLE
Drag and drop file to import (pla-research) no longer working

### ISSUE THREAD

**Issue by Kingkevin108** [Corvimae/pokemon-ranger#25]
I was using the drag and drop for the pla-research.json and it is no longer working. I drag onto the page and nothing happens now. 

Thank you for the work on this, it's fantastic!

**Comment by Corvimae** [comment]
Sorry, I changed the format of the file export and mentioned it in the Switch PSR server but not here.

Add this to the beginning of your file:
`{"activeTasks":  `

and then this to the end:
`}`

Feel free to attach your file and I can fix it.

**Comment by Kingkevin108** [comment]
Worked perfectly. Thank you for the swift response!
