### ISSUE TITLE
PLA Research Tasks: misc errors

### ISSUE THREAD

**Issue by free-muffin** [Corvimae/pokemon-ranger#27]
tentacool's second task is listed as "Times you've seen it use Fire Blast" when it should be a light specimen task
lopunny's catch goals are listed as 1, 2, 3, 4, 5 when they should be 1, 2, 4, 6, 10

**Comment by free-muffin** [comment]
mamoswine is also misspelled as mammoswine

**Comment by Corvimae** [comment]
Fixed, thanks!
