### ISSUE TITLE
weather conditions not calculated correctly

### ISSUE THREAD

**Issue by LoveSickHero** [Corvimae/pokemon-ranger#31]
![image](https://user-images.githubusercontent.com/116429783/197330676-069ba74c-840f-49b0-a33d-c6423fc137ed.png)
![image](https://user-images.githubusercontent.com/116429783/197330735-cfe49554-6bc5-4593-9ecd-7f484e207df0.png)
I tried using weatherBoosted=true and weatherReduced=true but the calculations do not change. I tried using True and WeatherReduced and weatherreduced but no changes either.

**Comment by Corvimae** [comment]
Could you share your mdr file?

**Comment by LoveSickHero** [comment]
https://www.dropbox.com/s/n7g7axg0h43shpb/charroute.mdr?dl=0 I hope this works. Not familiar with github

**Comment by Corvimae** [comment]
This should be fixed, thanks!
